## This code is used to postprocess the data generated by the simulation of the robot

# Processing is ensured using pandas since the data is stored in CSV files
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np

# Define the directory of the data files
data_directory = 'pc/ex7/data'

# Define the parameters of the experiment to plot
freq = "1.25"
amp = "50"
lag = "0.75"

# Initialize the variables for plotting
Time = []
X = []
Y = []
Speed = []
Stability = [] # ratio of points acquired to time

# Loop over all files in the directory
num_files = 0
for filename in os.listdir(data_directory):
    if filename.startswith('data_' + freq + '_' + amp + '_' + lag):
        num_files += 1
        # Read the CSV file
        df = pd.read_csv(os.path.join(data_directory, filename))

        # Extract the required features
        time = df['Time'] - df['Time'][0]
        x = df['X']
        y = df['Y']

        # Apply smoothing to the position data with a moving average filter
        window_size = 10
        x_smooth = np.convolve(x, np.ones(window_size) / window_size, mode='same')
        y_smooth = np.convolve(y, np.ones(window_size) / window_size, mode='same')

        # Compute the speed from the smoothed position data
        v = np.sqrt(np.diff(x_smooth)**2 + np.diff(y_smooth)**2) / np.diff(time)
        v = [v[i] if v[i] < 1 else 0 for i in range(len(v))] # Remove outliers

        # Append the data to the lists
        Time.append(time)
        X.append(x)
        Y.append(y)
        Speed.append(v)
        Stability.append((len(time)/ time[len(time)-1]))
        
print('Number of experiments found: ', num_files)
#Ask if plot is needed (to detect anormal number of experiments and avoid mistakes in file selection)
plot = input('Do you want to plot the data? (y/n): ')
if plot != 'y':
    exit()

# Create a figure with two subplots that share the x-axis
fig = plt.figure(figsize=(10, 7))
gs = fig.add_gridspec(2, 1, height_ratios=[3, 2])  # Adjust the height ratios to make the second subplot smaller
axs = gs.subplots(sharex=True)

# Plot the x trajectories for each experiment on the first subplot
for i in range(num_files):
    axs[0].plot(Time[i], X[i])
axs[0].set_title('X trajectories over time for freq: ' + freq + ', amp: ' + amp + ', lag: ' + lag)
axs[0].set_ylabel('X (m)')
axs[0].legend(['Experiment ' + str(i) for i in range(num_files)])

# Plot the speed for each experiment on the second subplot
for i in range(num_files):
    axs[1].plot(Time[i][1:], Speed[i])
axs[1].set_title('Speed over time for freq: ' + freq + ', amp: ' + amp + ', lag: ' + lag)
axs[1].set_xlabel('Time (s)')
axs[1].set_ylabel('Speed (m/s)')
axs[1].legend(['Experiment ' + str(i) for i in range(num_files)])

# Display the average speed for the experiments in the figure title
average_speed = np.mean([np.mean(Speed[i]) for i in range(num_files)])
fig.suptitle('Average speed: ' + str(round(average_speed, 2)) + ' m/s    ' + 'Measure of Stability: ' + str(round(np.mean(Stability), 2)) + ' points/s')

# Show the figure
plt.show()

# Save the figure as a PNG file if satisfied with the plot
save = input('Do you want to save the plot? (y/n): ')
if save == 'y':
    fig.savefig('pc/ex7/plots/plt_' + freq + '_' + amp + '_' + lag + '.png')
    print('Plot saved as plot.png')
